import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '*': 'vp fmt',
  },
  test: {
    clearMocks: true,
    coverage: {
      exclude: ['lib'],
      include: ['src/**/*.ts', 'src/**/*.js'],
      provider: 'istanbul',
      // The suite has known pre-existing kata failures; without this, no
      // coverage report is generated at all when tests fail.
      reportOnFailure: true,
      reporter: ['html', 'lcov'],
    },
    exclude: ['lib', 'node_modules'],
    includeSource: ['src/**/*.{js,ts}'],
    setupFiles: ['console-fail-test/setup'],
  },
  fmt: {
    arrowParens: 'avoid',
    bracketSpacing: true,
    ignorePatterns: ['coverage*/', 'lib/', 'pnpm-lock.yaml', '.all-contributorsrc'],
    'plugins-comments': {
      removed: ['prettier-plugin-curly'],
      see: ['https://github.com/JoshuaKGoldberg/prettier-plugin-curly'],
    },
    printWidth: 100,
    semi: false,
    singleQuote: true,
    sortPackageJson: {},
    tabWidth: 2,
    trailingComma: 'es5',
    useTabs: false,
  },
  lint: {
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: ['coverage*/**', 'lib/**', 'pnpm-lock.yaml'],
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    overrides: [
      {
        files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
        rules: {
          'constructor-super': 'error',
          'for-direction': 'error',
          'getter-return': 'error',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-class-assign': 'error',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-const-assign': 'error',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-class-members': 'error',
          'no-dupe-else-if': 'error',
          'no-dupe-keys': 'error',
          'no-duplicate-case': 'error',
          'no-empty': 'error',
          'no-empty-character-class': 'off',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-func-assign': 'error',
          'no-global-assign': 'error',
          'no-import-assign': 'error',
          'no-invalid-regexp': 'off',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-new-native-nonconstructor': 'error',
          'no-nonoctal-decimal-escape': 'error',
          'no-obj-calls': 'error',
          'no-prototype-builtins': 'error',
          'no-redeclare': 'error',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-setter-return': 'error',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-this-before-super': 'error',
          'no-unassigned-vars': 'error',
          'no-undef': 'error',
          'no-unexpected-multiline': 'off',
          'no-unreachable': 'error',
          'no-unsafe-finally': 'error',
          'no-unsafe-negation': 'error',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-unused-vars': 'error',
          'no-useless-assignment': 'error',
          'no-useless-backreference': 'off',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'no-with': 'error',
          'preserve-caught-error': 'error',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          'node/no-exports-assign': 'error',
          'perfectionist/sort-variable-declarations': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-intersection-types': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-array-includes': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-named-imports': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-named-exports': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-object-types': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-union-types': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-switch-case': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-interfaces': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-jsx-props': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-classes': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-exports': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-objects': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-enums': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-sets': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'perfectionist/sort-maps': [
            'error',
            {
              type: 'natural',
              order: 'asc',
            },
          ],
          'prefer-regex-literals': 'error',
          'regexp/confusing-quantifier': 'warn',
          'regexp/control-character-escape': 'error',
          'regexp/match-any': 'error',
          'regexp/negation': 'error',
          'regexp/no-contradiction-with-assertion': 'error',
          'regexp/no-dupe-characters-character-class': 'error',
          'regexp/no-dupe-disjunctions': 'error',
          'regexp/no-empty-alternative': 'warn',
          'regexp/no-empty-capturing-group': 'error',
          'regexp/no-empty-character-class': 'error',
          'regexp/no-empty-group': 'error',
          'regexp/no-empty-lookarounds-assertion': 'error',
          'regexp/no-empty-string-literal': 'error',
          'regexp/no-escape-backspace': 'error',
          'regexp/no-extra-lookaround-assertions': 'error',
          'regexp/no-invalid-regexp': 'error',
          'regexp/no-invisible-character': 'error',
          'regexp/no-lazy-ends': 'warn',
          'regexp/no-legacy-features': 'error',
          'regexp/no-misleading-capturing-group': 'error',
          'regexp/no-misleading-unicode-character': 'error',
          'regexp/no-missing-g-flag': 'error',
          'regexp/no-non-standard-flag': 'error',
          'regexp/no-obscure-range': 'error',
          'regexp/no-optional-assertion': 'error',
          'regexp/no-potentially-useless-backreference': 'warn',
          'regexp/no-super-linear-backtracking': 'error',
          'regexp/no-trivially-nested-assertion': 'error',
          'regexp/no-trivially-nested-quantifier': 'error',
          'regexp/no-unused-capturing-group': 'error',
          'regexp/no-useless-assertions': 'error',
          'regexp/no-useless-backreference': 'error',
          'regexp/no-useless-character-class': 'error',
          'regexp/no-useless-dollar-replacements': 'error',
          'regexp/no-useless-escape': 'error',
          'regexp/no-useless-flag': 'warn',
          'regexp/no-useless-lazy': 'error',
          'regexp/no-useless-non-capturing-group': 'error',
          'regexp/no-useless-quantifier': 'error',
          'regexp/no-useless-range': 'error',
          'regexp/no-useless-set-operand': 'error',
          'regexp/no-useless-string-literal': 'error',
          'regexp/no-useless-two-nums-quantifier': 'error',
          'regexp/no-zero-quantifier': 'error',
          'regexp/optimal-lookaround-quantifier': 'warn',
          'regexp/optimal-quantifier-concatenation': 'error',
          'regexp/prefer-character-class': 'error',
          'regexp/prefer-d': 'error',
          'regexp/prefer-plus-quantifier': 'error',
          'regexp/prefer-predefined-assertion': 'error',
          'regexp/prefer-question-quantifier': 'error',
          'regexp/prefer-range': 'error',
          'regexp/prefer-set-operation': 'error',
          'regexp/prefer-star-quantifier': 'error',
          'regexp/prefer-unicode-codepoint-escapes': 'error',
          'regexp/prefer-w': 'error',
          'regexp/simplify-set-operations': 'error',
          'regexp/sort-flags': 'error',
          'regexp/strict': 'error',
          'regexp/use-ignore-case': 'error',
          curly: 'off',
          'unicorn/empty-brace-spaces': 'off',
          'unicorn/no-nested-ternary': 'off',
          'unicorn/number-literal-case': 'off',
        },
        plugins: ['node'],
        env: {
          es2024: true,
        },
        globals: {
          __dirname: 'off',
          __filename: 'off',
          AbortController: 'readonly',
          AbortSignal: 'readonly',
          atob: 'readonly',
          Blob: 'readonly',
          BroadcastChannel: 'readonly',
          btoa: 'readonly',
          Buffer: 'readonly',
          ByteLengthQueuingStrategy: 'readonly',
          clearImmediate: 'readonly',
          clearInterval: 'readonly',
          clearTimeout: 'readonly',
          CloseEvent: 'readonly',
          CompressionStream: 'readonly',
          console: 'readonly',
          CountQueuingStrategy: 'readonly',
          crypto: 'readonly',
          Crypto: 'readonly',
          CryptoKey: 'readonly',
          CustomEvent: 'readonly',
          DecompressionStream: 'readonly',
          DOMException: 'readonly',
          Event: 'readonly',
          EventTarget: 'readonly',
          exports: 'off',
          fetch: 'readonly',
          File: 'readonly',
          FormData: 'readonly',
          global: 'readonly',
          Headers: 'readonly',
          MessageChannel: 'readonly',
          MessageEvent: 'readonly',
          MessagePort: 'readonly',
          module: 'off',
          navigator: 'readonly',
          Navigator: 'readonly',
          performance: 'readonly',
          Performance: 'readonly',
          PerformanceEntry: 'readonly',
          PerformanceMark: 'readonly',
          PerformanceMeasure: 'readonly',
          PerformanceObserver: 'readonly',
          PerformanceObserverEntryList: 'readonly',
          PerformanceResourceTiming: 'readonly',
          process: 'readonly',
          queueMicrotask: 'readonly',
          ReadableByteStreamController: 'readonly',
          ReadableStream: 'readonly',
          ReadableStreamBYOBReader: 'readonly',
          ReadableStreamBYOBRequest: 'readonly',
          ReadableStreamDefaultController: 'readonly',
          ReadableStreamDefaultReader: 'readonly',
          Request: 'readonly',
          require: 'off',
          Response: 'readonly',
          setImmediate: 'readonly',
          setInterval: 'readonly',
          setTimeout: 'readonly',
          structuredClone: 'readonly',
          SubtleCrypto: 'readonly',
          TextDecoder: 'readonly',
          TextDecoderStream: 'readonly',
          TextEncoder: 'readonly',
          TextEncoderStream: 'readonly',
          TransformStream: 'readonly',
          TransformStreamDefaultController: 'readonly',
          URL: 'readonly',
          URLSearchParams: 'readonly',
          WebAssembly: 'readonly',
          WebSocket: 'readonly',
          WritableStream: 'readonly',
          WritableStreamDefaultController: 'readonly',
          WritableStreamDefaultWriter: 'readonly',
        },
        jsPlugins: ['eslint-plugin-perfectionist', 'eslint-plugin-regexp'],
      },
      {
        files: ['**/*.md'],
        rules: {},
        jsPlugins: [],
      },
      {
        env: {
          node: true,
        },
        files: ['**/*.{js,mjs,cjs,ts,mts,cts}'],
        jsPlugins: ['eslint-plugin-no-only-tests', 'eslint-plugin-perfectionist'],
        plugins: ['import'],
        rules: {
          'import/extensions': ['error', 'ignorePackages'],
          'no-only-tests/no-only-tests': 'error',
          'no-case-declarations': 'off',
          'no-constant-condition': 'off',
          'no-inner-declarations': 'off',
          'perfectionist/sort-classes': [
            'error',
            {
              groups: [
                'index-signature',
                'static-property',
                'private-property',
                'property',
                'constructor',
                'static-method',
                'private-method',
                'method',
              ],
              order: 'asc',
              type: 'natural',
            },
          ],
          'perfectionist/sort-objects': [
            'error',
            {
              order: 'asc',
              partitionByComment: true,
              type: 'natural',
            },
          ],
        },
      },
      {
        files: ['**/*.ts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
          'no-array-constructor': 'error',
          'no-unused-expressions': 'error',
          'no-unused-vars': 'error',
          'no-useless-constructor': 'error',
          'typescript/ban-ts-comment': [
            'error',
            {
              minimumDescriptionLength: 10,
            },
          ],
          'typescript/no-duplicate-enum-values': 'error',
          'typescript/no-dynamic-delete': 'error',
          'typescript/no-empty-object-type': 'error',
          'typescript/no-explicit-any': 'error',
          'typescript/no-extra-non-null-assertion': 'error',
          'typescript/no-extraneous-class': 'error',
          'typescript/no-invalid-void-type': 'error',
          'typescript/no-misused-new': 'error',
          'typescript/no-namespace': 'error',
          'typescript/no-non-null-asserted-nullish-coalescing': 'error',
          'typescript/no-non-null-asserted-optional-chain': 'error',
          'typescript/no-non-null-assertion': 'error',
          'typescript/no-require-imports': 'error',
          'typescript/no-this-alias': 'error',
          'typescript/no-unnecessary-type-constraint': 'error',
          'typescript/no-unsafe-declaration-merging': 'error',
          'typescript/no-unsafe-function-type': 'error',
          'typescript/no-wrapper-object-types': 'error',
          'typescript/prefer-as-const': 'error',
          'typescript/prefer-literal-enum-member': 'error',
          'typescript/prefer-namespace-keyword': 'error',
          'typescript/triple-slash-reference': 'error',
          'typescript/unified-signatures': 'error',
          'no-empty-function': 'error',
          'typescript/adjacent-overload-signatures': 'error',
          'typescript/array-type': 'error',
          'typescript/ban-tslint-comment': 'error',
          'typescript/class-literal-property-style': 'error',
          'typescript/consistent-generic-constructors': 'error',
          'typescript/consistent-indexed-object-style': 'error',
          'typescript/consistent-type-assertions': 'error',
          'typescript/consistent-type-definitions': 'error',
          'typescript/no-confusing-non-null-assertion': 'error',
          'typescript/no-inferrable-types': 'error',
          'typescript/prefer-for-of': 'error',
          'typescript/prefer-function-type': 'error',
          'jsdoc/check-access': 'error',
          'jsdoc/check-property-names': 'error',
          'jsdoc/check-tag-names': [
            'error',
            {
              typed: true,
            },
          ],
          'jsdoc/empty-tags': 'error',
          'jsdoc/implements-on-classes': 'error',
          'jsdoc/no-defaults': 'error',
          'jsdoc/require-param': 'off',
          'jsdoc/require-param-description': 'error',
          'jsdoc/require-param-name': 'error',
          'jsdoc/require-param-type': 'off',
          'jsdoc/require-property': 'off',
          'jsdoc/require-property-description': 'error',
          'jsdoc/require-property-name': 'error',
          'jsdoc/require-property-type': 'off',
          'jsdoc/require-returns': 'off',
          'jsdoc/require-returns-description': 'error',
          'jsdoc/require-returns-type': 'off',
          'jsdoc/require-yields': 'error',
          'typescript/no-deprecated': 'error',
          'no-implied-eval': 'off',
          'no-throw-literal': 'off',
          'prefer-promise-reject-errors': 'off',
          'require-await': 'off',
          'typescript/await-thenable': 'error',
          'typescript/no-array-delete': 'error',
          'typescript/no-base-to-string': 'error',
          'typescript/no-confusing-void-expression': 'error',
          'typescript/no-duplicate-type-constituents': 'error',
          'typescript/no-floating-promises': 'error',
          'typescript/no-for-in-array': 'error',
          'typescript/no-implied-eval': 'error',
          'typescript/no-meaningless-void-operator': 'error',
          'typescript/no-misused-promises': 'error',
          'typescript/no-misused-spread': 'error',
          'typescript/no-mixed-enums': 'error',
          'typescript/no-redundant-type-constituents': 'error',
          'typescript/no-unnecessary-boolean-literal-compare': 'error',
          'typescript/no-unnecessary-condition': [
            'error',
            {
              allowConstantLoopConditions: true,
            },
          ],
          'typescript/no-unnecessary-template-expression': 'error',
          'typescript/no-unnecessary-type-arguments': 'error',
          'typescript/no-unnecessary-type-assertion': 'error',
          'typescript/no-unnecessary-type-conversion': 'error',
          'typescript/no-unnecessary-type-parameters': 'error',
          'typescript/no-unsafe-argument': 'error',
          'typescript/no-unsafe-assignment': 'error',
          'typescript/no-unsafe-call': 'error',
          'typescript/no-unsafe-enum-comparison': 'error',
          'typescript/no-unsafe-member-access': 'error',
          'typescript/no-unsafe-return': 'error',
          'typescript/no-unsafe-unary-minus': 'error',
          'typescript/no-useless-default-assignment': 'error',
          'typescript/only-throw-error': 'error',
          'typescript/prefer-promise-reject-errors': 'error',
          'typescript/prefer-reduce-type-parameter': 'error',
          'typescript/prefer-return-this-type': 'error',
          'typescript/related-getter-setter-pairs': 'error',
          'typescript/require-await': 'error',
          'typescript/restrict-plus-operands': [
            'error',
            {
              allowAny: false,
              allowBoolean: false,
              allowNullish: false,
              allowNumberAndString: false,
              allowRegExp: false,
            },
          ],
          'typescript/restrict-template-expressions': [
            'error',
            {
              allowAny: false,
              allowBoolean: false,
              allowNever: false,
              allowNullish: false,
              allowNumber: false,
              allowRegExp: false,
            },
          ],
          'typescript/return-await': ['error', 'error-handling-correctness-only'],
          'typescript/unbound-method': 'error',
          'typescript/use-unknown-in-catch-callback-variable': 'error',
          'typescript/dot-notation': 'off',
          'typescript/non-nullable-type-assertion-style': 'error',
          'typescript/prefer-find': 'error',
          'typescript/prefer-includes': 'error',
          'typescript/prefer-nullish-coalescing': 'error',
          'typescript/prefer-optional-chain': 'error',
          'typescript/prefer-regexp-exec': 'error',
          'typescript/prefer-string-starts-ends-with': 'error',
        },
        plugins: ['jsdoc'],
      },
      {
        // Practice-repo idioms: bare REPL-style output expressions and
        // partially-unused `import.meta.vitest` destructures in in-source tests.
        files: ['src/**'],
        rules: {
          'no-unused-expressions': 'off',
          'no-unused-vars': 'error',
        },
      },
      {
        files: ['**/*.test.ts'],
        rules: {
          'vitest/expect-expect': 'error',
          'vitest/no-commented-out-tests': 'error',
          'vitest/no-conditional-expect': 'error',
          'vitest/no-disabled-tests': 'warn',
          'vitest/no-focused-tests': 'error',
          'vitest/no-identical-title': 'error',
          'vitest/no-import-node-test': 'error',
          'vitest/no-interpolation-in-snapshots': 'error',
          'vitest/no-mocks-import': 'error',
          'vitest/no-standalone-expect': 'error',
          'vitest/no-unneeded-async-expect-function': 'error',
          'vitest/prefer-called-exactly-once-with': 'error',
          'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
          'vitest/valid-describe-callback': 'error',
          'vitest/valid-expect': 'error',
          'vitest/valid-expect-in-promise': 'error',
          'vitest/valid-title': 'error',
          'typescript/no-unsafe-assignment': 'off',
          'typescript/no-unsafe-call': 'off',
        },
        plugins: ['vitest'],
      },
      {
        files: ['*.json', '*.jsonc'],
        rules: {
          'no-unused-expressions': 'off',
          'no-unused-vars': 'off',
          'jsonc/comma-dangle': 'error',
          'jsonc/no-bigint-literals': 'error',
          'jsonc/no-binary-expression': 'error',
          'jsonc/no-binary-numeric-literals': 'error',
          'jsonc/no-comments': 'error',
          'jsonc/no-dupe-keys': 'error',
          'jsonc/no-escape-sequence-in-identifier': 'error',
          'jsonc/no-floating-decimal': 'error',
          'jsonc/no-hexadecimal-numeric-literals': 'error',
          'jsonc/no-infinity': 'error',
          'jsonc/no-multi-str': 'error',
          'jsonc/no-nan': 'error',
          'jsonc/no-number-props': 'error',
          'jsonc/no-numeric-separators': 'error',
          'jsonc/no-octal-numeric-literals': 'error',
          'jsonc/no-octal': 'error',
          'jsonc/no-parenthesized': 'error',
          'jsonc/no-plus-sign': 'error',
          'jsonc/no-regexp-literals': 'error',
          'jsonc/no-sparse-arrays': 'error',
          'jsonc/no-template-literals': 'error',
          'jsonc/no-undefined-value': 'error',
          'jsonc/no-unicode-codepoint-escapes': 'error',
          'jsonc/no-useless-escape': 'error',
          'jsonc/quote-props': 'error',
          'jsonc/quotes': 'error',
          'jsonc/space-unary-ops': 'error',
          'jsonc/valid-json-number': 'error',
          'jsonc/vue-custom-block/no-parsing-error': 'error',
          'jsonc/sort-keys': 'error',
        },
        jsPlugins: ['eslint-plugin-jsonc'],
      },
      {
        files: ['*.jsonc'],
        rules: {
          'jsonc/no-comments': 'off',
        },
        jsPlugins: ['eslint-plugin-jsonc'],
      },
      {
        files: ['**/*.{yml,yaml}'],
        rules: {
          'yml/block-mapping-question-indicator-newline': 'off',
          'yml/block-mapping': 'error',
          'yml/block-sequence-hyphen-indicator-newline': 'off',
          'yml/block-sequence': 'error',
          'yml/flow-mapping-curly-newline': 'off',
          'yml/flow-mapping-curly-spacing': 'off',
          'yml/flow-sequence-bracket-newline': 'off',
          'yml/flow-sequence-bracket-spacing': 'off',
          'yml/indent': 'off',
          'yml/key-spacing': 'off',
          'yml/no-empty-document': 'error',
          'yml/no-empty-key': 'error',
          'yml/no-empty-mapping-value': 'error',
          'yml/no-empty-sequence-entry': 'error',
          'yml/no-irregular-whitespace': 'error',
          'yml/no-tab-indent': 'error',
          'yml/plain-scalar': 'error',
          'yml/quotes': 'off',
          'yml/spaced-comment': 'error',
          'yml/vue-custom-block/no-parsing-error': 'error',
          'yml/block-mapping-colon-indicator-newline': 'off',
          'yml/no-multiple-empty-lines': 'off',
          'yml/no-trailing-zeros': 'off',
          'yml/file-extension': [
            'error',
            {
              extension: 'yml',
            },
          ],
          'yml/sort-keys': [
            'error',
            {
              order: {
                type: 'asc',
              },
              pathPattern: '^.*$',
            },
          ],
          'yml/sort-sequence-values': [
            'error',
            {
              order: {
                type: 'asc',
              },
              pathPattern: '^.*$',
            },
          ],
        },
        jsPlugins: ['eslint-plugin-yml'],
      },
    ],
    plugins: ['oxc', 'typescript', 'unicorn', 'react'],
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
  },
})
