name: Generate Repository Diagram

on:
  push:
    branches:
      - main # replace with your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: ./assets/images/diagram.svg
