name: Generate Repository Diagram

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/images/diagram.svg'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.DIAGRAM_TOKEN }}

      - name: Generate diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: ./assets/images/diagram.svg
          token: ${{ secrets.DIAGRAM_TOKEN }}
